name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'

    - name: Build
      run: GOARCH=${{ matrix.architecture }} go build -ldflags="-s -w" -o nat-go-${{ matrix.architecture }} -v ./...

    - name: Test
      run: go test -v ./...

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Upload release asset
      uses: ncipollo/release-action@v1
      with:
        files: |
          nat-go-amd64
          nat-go-arm64
