name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # 添加 tag 触发器
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'

    - name: Build
      run: GOARCH=${{ matrix.architecture }} go build -ldflags="-s -w" -o nat-go-${{ matrix.architecture }} -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload artifacts  # 添加构建产物上传
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: nat-go-*

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')  # 仅在有 tag 时运行
    steps:
    - name: Download artifacts  # 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: binaries

    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "nat-go-*"  # 使用正确的参数名
        tag: ${{ github.ref_name }}  # 使用触发的 tag
        token: ${{ secrets.GITHUB_TOKEN }}